version: '1.0'
services:
  neo4j:
    container_name: neo4j-server
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - data:/data
      - plugins:/plugins
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_apoc_export_file_enabled: 'true'
      NEO4J_apoc_import_file_enabled: 'true'
      NEO4J_apoc_import_file_use__neo4j__config: 'true'
      NEO4J_dbms_security_procedures_unrestricted: apoc.*

volumes:
  data:
    driver: local
  plugins:
    driver: local
